name: Integration
on:
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
      - gradle/libs.versions.toml
      - gradle/wrapper/
  workflow_dispatch:
env:
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # --------------------------------- Stage 1 ----------------------------------
  gradle-wrapper-validation:
    name: Gradle wrapper validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2
  # --------------------------------- Stage 2 ----------------------------------
  application-checks:
    name: Application checks
    runs-on: ubuntu-latest
    needs: gradle-wrapper-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Check application
        run: ./gradlew :app:check --no-daemon
  core-checks:
    name: Core checks
    runs-on: ubuntu-latest
    needs: gradle-wrapper-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Check application
        run: ./gradlew :core:check --no-daemon
