name: Integration
on:
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
      - gradle/libs.versions.toml
      - gradle/wrapper/
  workflow_dispatch:
jobs:
  checks:
    name: Application checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2
      - name: Check application
        run: ./gradlew :app:check --no-daemon
